### ISSUE TITLE
Add support for version

### ISSUE THREAD

**Issue by farcaller** [google/kasane#14]
As uncovered in #13, it'd be nice to have a `version` command to report the current kasane version.

**Comment by danishprakash** [comment]
I would like to work on this @farcaller. Is there anything else I should be aware of before beginning to work on this?

**Comment by farcaller** [comment]
It should be pretty straightforward to implement. I'd prefer a `--version` flag to the bare kasane (e.g. `kasane --version`) as an interface and you can use `setup.py` as the source of truth for the version number.
